# Generated by Django 5.0.1 on 2026-03-23 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=20)),
                ('cgpa', models.FloatField()),
                ('skills', models.IntegerField(default=0)),
                ('academics', models.IntegerField(default=0)),
                ('practice', models.IntegerField(default=0)),
                ('projects', models.IntegerField(default=0)),
                ('aptitude', models.IntegerField(default=0)),
                ('achievements', models.TextField(default='[]')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
