# Generated by Django 5.0.1 on 2026-03-24 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='placed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='achievements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.IntegerField(),
        ),
    ]
