# Generated by Django 5.0.1 on 2026-03-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_student_placed_alter_student_achievements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
