# Generated by Django 6.0.3 on 2026-04-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_student_company_student_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="applied_companies",
            field=models.TextField(blank=True, null=True),
        ),
    ]
