# Generated by Django 6.0.3 on 2026-04-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_student_applied_companies"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                ("requirements", models.TextField()),
                ("min_cgpa", models.FloatField(default=0.0)),
                ("min_skills_score", models.IntegerField(default=0)),
                ("min_academics_score", models.IntegerField(default=0)),
                ("salary", models.CharField(blank=True, max_length=100, null=True)),
                ("positions_available", models.IntegerField(default=1)),
                ("roles", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
